APPROACH=$1
HIDING=$2
cmake \
  -DCMAKE_CXX_COMPILER="/opt/intel/oneapi/compiler/2024.0/bin/icpx" \
  -DCMAKE_CXX_FLAGS=" -lmpi -Wno-deprecated -fsycl -fsycl-targets=intel_gpu_pvc -O3" \
  -DSYCL_RUNTIME=DPCPP \
  -DSYNERGY_SYCL_IMPL="DPC++" \
  -DSYNERGY_KERNEL_PROFILING=ON \
  -DSYNERGY_DEVICE_PROFILING=ON \
  -DSYNERGY_HOST_PROFILING=OFF \
  -DSYNERGY_USE_PROFILING_ENERGY=ON \
  -DSYNERGY_LZ_SUPPORT=ON \
  -DMPI_AS_LIBRARY=OFF \
  -DSYNERGY_BUILD_SAMPLES=ON \
  -DSYNERGY_SAMPLES_LZ_ARCH="pvc" \
  -DCLOVERLEAF_PRINT=OFF \
  -DFREQ_SCALING_APPROACH="$APPROACH" \
  -DMPI_HIDING=$HIDING \
  ..